application: androidversionproxy
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest

skip_files:
- ^(android_sample/.*)

env_variables:
  play_store_url: 'https://play.google.com/store/apps/details?id=com.google.android.ears'